name: todo
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^1.0.0-next.5

  cupertino_icons: ^1.0.2

 
 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

